# Generated by Django 3.2.6 on 2021-08-20 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.IntegerField(verbose_name='Cena [zł]'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_name',
            field=models.CharField(max_length=120, verbose_name='Usługa'),
        ),
        migrations.AlterField(
            model_name='service',
            name='time_of_service',
            field=models.FloatField(verbose_name='Czas [h]'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(verbose_name='Termin wizyty')),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.service', verbose_name='Usługa')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.user', verbose_name='Klient')),
            ],
        ),
    ]
