# Generated by Django 3.2.6 on 2021-08-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_service_service_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
